---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: besend-secrets
  namespace: besend
spec:
  encryptedData:
    db-password: AgAQRp+nW6i3x/8lfaES+lQDfZ0Nip7cFvtwxBsPd4t12eXwI8vN7mdtM9lgalgxY6HMqRVv96kg1H1AkYzq6sZ+pmKZzmkpBvmpsi6mKayXkcXZdnO6rpCJYNFoy/+qmHfeVfNcsNgoMtiCEbUO7l7NGk5mU6PwJ1g3tdg3mxZRlNq9kLTCO3HNd4R0uvly557zeUHumOux8CRRgWdGCBmDF9w2gJgTslnQAkS1Yxz6uq5n+BBMyrG6+AbR6Wi/LIfoUf5vZw6rQJjOowIvhw5Z5CrDi4M9GojxgrhwJrweMU3m8I1BYC2il1lfQK+qmrN/cKo1ZZoITLb/XhaqTD+cZPkzP8mTjP3VyLeHbVs/aKoHuJqxlG5qLQf3dgyDLRl7rI86Sup0giHIc6bGr1mYvR/tf15Bl4ECyoHWPHNAVI6RZVA+8DqaXCAGmYrxwQscyawYoUPes75uhXBZJ4IW9URB4sQnrOlEStyArZ3zsCqWiStsmfZG9yvma1rtA8DEmWe6Ar9JzKhkAVG5TSDfiGmlE5Sohn9RLmBQccmbp05zyJ8/RHUiffYG0bKmXBoOCP5O5c6u9RWVX59r3oTqI+TXyq5Ma1G+1kAyhFOIotgUSPXJwCylg4yhppjJT3pC9HrEqQEqSeUlmRSWpQWga11IuPHb1LmOqcXEcllk8Tjne/t/nFvthHgXYzUls3elsatBPe+ulcX+1cC8qOtloID06bD+t6FLZA==
    jwt-secret: AgCEglETJUeg8aKrk+mD+xsb6uCOAH3CCgJbcdvsnHYqCzeXO0m4Joebvkgc8czF5QiQwsLmb702QM2+9VUq9eNTS6gUngJVTW8v/UPWMy3IGjzIrcsKssizERdSwNe+ACqA9z6X6fWi30QBIANigWfB5jgmq+EpRkH3GrKLVzqbCiPODxcmaMlg4bb2Ku6EWW1Vmha47HKWcPFbLlRn4uIVj7RM7yWAsXA4riJHgDvuv7EVV9Vgp7rXDQ6LTD7z0nTW569dFrA2oMxy/Lh8zjulmcKjgo4dieAR8TOhipINjMdVETvHrL3TsMqk7WE2puj9hh2kQwht26lXkgYsbiMLLyr4nUjtlpQvzxNxnl29jzpWMFVK8avDrx2pkTizw3/vioSWUnnwheygxbP/Tjhs+JUl6TzQhYVJIEKAWzjG9xJWxDqQfDISsrt6eEM9zjUWU+qcGN41IOAsOCCLq5lezd8rEttslaoHJrcJdzvLP2+NIC5MiYOIN+HYPbo9eHhWVEWLFMv9QuE1CbB0MshmtQL9Qull3VDvGdLASM3PsbgnT/CGUn4VNrvY2rFjhoN7eEpSBLxi3jU97x2D5WOgGfGIP0FYghr0hWGjKwECXMPEh4onCUiymHMmfSpOPRZkoL4A7WDHO7egVB4Nv+uJ6G+kZ9SyMEU88lcwCDvh9bfhXaF1AX9gq+Jpb7dLCV/U77RPMYldq6slxpcqKZwUvP0ZQqwvJiSPzN+8QprPbS6fGSu+I4jdbkbU4A==
  template:
    metadata:
      name: besend-secrets
      namespace: besend
    type: Opaque
