apiVersion: v1
kind: ServiceAccount
metadata:
  name: besend-operator
  namespace: besend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: besend-operator-role
rules:
- apiGroups: ["email.example.com"]
  resources: ["emails", "emailsenderconfigs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["email.example.com"]
  resources: ["emails/status", "emailsenderconfigs/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: besend-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: besend-operator-role
subjects:
- kind: ServiceAccount
  name: besend-operator
  namespace: besend
