---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: besend
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBjw9TyObPgr5RrMB7KP6tTAMN2dcUqb6fnBayQFmKSmyKpSa47+03z/PPJyqtZ9D5Ly6q7vOIhvztviCeannUXtn55c2FOMtqQFYN8IHmebzjUv6qznVRhW4UmbrB9RQBhzLl7iZQ/mLrV0Zl16mPWGI58AoRb/n8t7yjdmR72PUzLZvyCpbwfz+8avZDBqoNuELvzfjKtpPpS/BzaGlm7avfzV5Q0UMxZaFp4c/pIejIE7qRkiT8Ft47xFSb1g5BZg5xbPLb+m0+7e66fS1DfjuEpD3vnbS1knGJEPHZ1+5Zq08q65Fs1DBFKaJR1nZjyrgwB4Gp91CoJage4SEQLAiZz4ubuZ3V8EZ2BKk9Ih12NGzriI52Y4NCP/WI4fguH2kbrVoGNVZS9cp3YjMdf7e6MnV0k1o3pnOdI6oNVlUwmaexm6ThDqwllFGxbs2C4rUlXh4o3DETqAQ7GLN2OEfJjkkHh0gLx5XhJ94g4zdAzwg3HXH8ykv8PP1GWAPBBuXwANbaGnpY0Zg8GQsgxNHJ6h1hDPqS1ZedPBxl/Xli6ApBqtGyd72tdXYxkMZNOCdEizPVRV5IMvlJ642cEier+X5by5lDJwsMsIHdnLrsnheOTZC5G6sSJ9XXVZO9j/jMrE786W+8TJ4wP+xOCSjVeXZSwHotfB8YdiID2qwX3nTjd1pAkNpsZM9q8lgBWAKkKmz9XqXuzeMMFi+oUOGNtAzANSFdGvw==
  template:
    metadata:
      name: postgres-secret
      namespace: besend
    type: Opaque
