---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: resend-api-key
  namespace: besend
spec:
  encryptedData:
    password: AgB+zUnEy5bbjf3cf6OUHH2UbFmAYnJO9MzgBUzLFJjfBCtaCJPFb2SXvx4zWlv6J+ANOJg5gWVCnXhcl/T2n5L41PQSh9qhzTzbURRNDvMzOpo5pHRJE+oY92pzG51UVA/l6UQ9hx6XPLWXYJ5X1TjoeVSggr9sRvaVrOR/ODZptCiy03nmWfhnolL7ucdacKP04IdbWbC2Y23Xu/G5+B2b+fOhnn4pHiBsLVVm48ftafNaYKxuW1TgAGsWU3VPnC58rOS+RjHMpwbeLA1e0jAwvRpIOgiM9jV+1RlsIfH6rVKFnGfCWDvmKfn1t/usuBnPS18dlxREmW9Jsiudcp2P3YMMZM7X8+FHlE5rkVMGukb/YsF5h08UtfiDnGj5f1c0k608EX/TuiKP/v3YzjsLz11GtgtXoGLoLkxjbuHZQT5Y/MwwlsMrAQl2GHL0cmFtYc//5vfofpi+6J/AhngKOjb0MSSKMuG4fr1EBxu4oVeTGK7whtQa1LI6ntjE8eLT31HmdMl1dGUwOr+HDWM9JvA7T4vrC3mjsjpQXqwZAQNIt3dBAa0dymIN8mFTKmaPWVnB4xgMhyYVA2CvM3fVLg0nOYUfmw6okwFK8KHkfdqWdXdydqRTzQUyYngepvNiZDIl1MqXVW7jUrVa6z1Y3J17S6yb2mfurUxhIkvHdAiqj94YpGFCFqfq2SuwQCaZBZOjcscCebrNyoYrM2p68aTIl720ZKwhhvaLcFJUF6yz3xI=
  template:
    metadata:
      name: resend-api-key
      namespace: besend
    type: Opaque
