---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: resend-api-key
  namespace: besend
spec:
  encryptedData:
    password: AgACNd0vFSsvSUx08nb5KLJVMFsEQnGTkRkvImMilzIE+nUKHgw7ZAJ4wfeU4Oxb43wTC5pT0Zz//rLbBEvG532oOrpQiwEOq3qvFJNXqoBqxPtADjMOqwOWV/dAu7LMe3z8m6cw8BdJ/wjh1f5MqtM5KvcijbNtP+eVdPbRz/6zFBI7WWO8xGqfjlwFgVs5DH5Q2hWRkruaYpPftPs63jaouKB79KIhgpXtKjKfVNuyJjyUi+7m7Kp0mrCCPJ0MsrrI5g0tqXsTifT6mOpnPu4DKs0MNmsj30CCSgQFNpKx4Jep1vYhduPMQBBlSfw6ldvkl+8sK+xwWEiWWz64+Y3y8YS4gSsGGL9UxS8z9pWApp97jPFrF8voRUZLuw+6zKiadv+QQi57S8mc5iZPaJ0VYfMrxKgI7JEH98Sm76Z46SDY7J3DLAN0GzBy1VOKc3xE89vBtTAESRZR7h1ZgSYaHoOkQl48yHWeQubY5G8YHKT3+KBUOv56fYWERUBhwdlLJM0nOEWwaEOInx2n2ZcPE5ME6NzxHcJv2sLDCt31uiuLG/EcXN43hVEZKqrbUcr29GEGCh5IEFVQRAYiU6J3H9A86C/FOM1mydjb9dX0+Qk1E4gVzP57KVYbW9jmowTaVbLIF204GYhrrprIgGq5o9Nb4j02iUlGBRS1/g043zspE58UpJfoLBXGv5KN9mU5BaOQI4fCD1i6/P/3/LoTo1g2GAicXBt0uVEkguDNdgSbcOo=
  template:
    metadata:
      name: resend-api-key
      namespace: besend
    type: Opaque
