apiVersion: email.example.com/v1alpha1
kind: EmailSenderConfig
metadata:
  name: mailhog-config
  namespace: email-system
spec:
  provider: native-smtp
  apiTokenSecretRef: "mailhog-secret"
  senderEmail: "noreply@besend.io"
  fromName: "Besend Notifications"
  domain: "mailhog.email-system.svc.cluster.local"
  port: 1025
  timeout: 30
