apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-operator
  namespace: email-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-operator
  template:
    metadata:
      labels:
        app: email-operator
    spec:
      serviceAccountName: email-operator
      containers:
      - name: manager
        image: gatete/besend:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 8081
          name: health
